#!/bin/bash
#
## getapod: download Astronomy Picture Of the Day
## ----------------------------------------------
## Simple script getting fresh picture from http://apod.nasa.gov
## Add it as a cron job, e.g.:
## 
##      0 6,10 * * * /home/mich/bin/getapod
##
## Point your screensaver to ~/apod and set slideshow :-)
## Or, alternatively use only 'today.jpg'
## The script automatically removes pictures older than 2 weeks.
## It downloads only images, not videos nor any active content.

APODIR=$HOME/apod
APOD=http://apod.nasa.gov

# init 
[ -d $APODIR ] || mkdir $APODIR
cd $APODIR

# get index file parse/search for image (big version)
wget $APOD/$1 -O index.html
IM=`grep -ai '<A HREF="image/' index.html |cut -d\" -f2`
IMB=`basename $IM`
wget $APOD/$IM -O $IMB     ## -O to prevent backups
cp $IMB today.jpg

# cleanup (e.g. last two weeks only)
# assumes wget set timestamp accordingly
find . -mtime +14 -exec rm {} \;

